// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

// Injectors from wire.go:

func InitBootstrap() *Bootstrap {
	bootstrap := NewBootstrap()
	return bootstrap
}
