app:
  debug: false
server:
  http:
    port: 8080
  prefork: false
database:
  DBType: mysql
  Username: root
  Password: root
  Host: 127.0.0.1:3306
  DBName: thinkcmf
  TablePrefix: cmf_
  Charset: utf8mb4
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenConns: 30
