app:
  debug: false
server:
  http:
    port: 8080
  prefork: false
database:
  DBType: mysql
  Username: root
  Password: 123456Aa?
  Host: 172.17.0.9:3306
  DBName: cardsys
  TablePrefix: cmf_
  Charset: utf8mb4
  ParseTime: true
  MaxIdleConns: 10000
  MaxOpenConns: 20000
