package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"

	"github.com/wuwuseo/cmf/app/internal/genutil"
)

type schemaType struct {
	name       string
	importPath string
	alias      string
}

var appCodePattern = regexp.MustCompile(`^[a-z][a-z0-9]*$`)

func main() {
	dir := flag.String("apps-dir", ".", "feature set directory")
	out := flag.String("out", "../ent/schema/zz_apps_gen.go", "generated Ent schema file")
	pkg := flag.String("pkg", "schema", "output package")
	flag.Parse()
	if err := generate(*dir, *out, *pkg); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(dir, out, pkg string) error {
	base, err := genutil.ModuleImport(dir)
	if err != nil {
		return err
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	var types []schemaType
	seen := map[string]bool{}
	for _, entry := range entries {
		if !entry.IsDir() || strings.HasPrefix(entry.Name(), ".") {
			continue
		}
		if !appCodePattern.MatchString(entry.Name()) {
			return fmt.Errorf("invalid app directory %q", entry.Name())
		}
		if _, err := os.Stat(filepath.Join(dir, entry.Name(), "app.go")); os.IsNotExist(err) {
			continue
		} else if err != nil {
			return err
		}
		schemaDir := filepath.Join(dir, entry.Name(), "schema")
		if _, err := os.Stat(schemaDir); os.IsNotExist(err) {
			continue
		} else if err != nil {
			return err
		}
		files, err := filepath.Glob(filepath.Join(schemaDir, "*.go"))
		if err != nil {
			return err
		}
		sort.Strings(files)
		appTypes := map[string]bool{}
		var edgeTargets []string
		for _, file := range files {
			if strings.HasSuffix(file, "_test.go") {
				continue
			}
			parsed, err := parser.ParseFile(token.NewFileSet(), file, nil, 0)
			if err != nil {
				return err
			}
			for _, decl := range parsed.Decls {
				if fn, ok := decl.(*ast.FuncDecl); ok && fn.Name.Name == "Edges" && fn.Body != nil {
					ast.Inspect(fn.Body, func(node ast.Node) bool {
						sel, ok := node.(*ast.SelectorExpr)
						if !ok || sel.Sel.Name != "Type" {
							return true
						}
						if ident, ok := sel.X.(*ast.Ident); ok {
							edgeTargets = append(edgeTargets, ident.Name)
						} else {
							edgeTargets = append(edgeTargets, "<external>")
						}
						return true
					})
				}
				gen, ok := decl.(*ast.GenDecl)
				if !ok || gen.Tok != token.TYPE {
					continue
				}
				for _, spec := range gen.Specs {
					typ := spec.(*ast.TypeSpec)
					st, ok := typ.Type.(*ast.StructType)
					if !ok || !embedsEntSchema(st) {
						continue
					}
					prefix := string(unicode.ToUpper(rune(entry.Name()[0]))) + entry.Name()[1:]
					if !ast.IsExported(typ.Name.Name) || !strings.HasPrefix(typ.Name.Name, prefix) || len(typ.Name.Name) == len(prefix) || seen[typ.Name.Name] {
						return fmt.Errorf("invalid or duplicate schema type %s in %s: name must start with %s", typ.Name.Name, file, prefix)
					}
					seen[typ.Name.Name] = true
					appTypes[typ.Name.Name] = true
					types = append(types, schemaType{typ.Name.Name, base + "/" + entry.Name() + "/schema", "appschema" + entry.Name()})
				}
			}
		}
		for _, target := range edgeTargets {
			if !appTypes[target] {
				return fmt.Errorf("app %s: edge target %s must be in the same feature set", entry.Name(), target)
			}
		}
	}
	if err := checkLocalCollisions(filepath.Dir(out), out, seen); err != nil {
		return err
	}
	sort.Slice(types, func(i, j int) bool { return types[i].name < types[j].name })
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by entgen; DO NOT EDIT.\npackage %s\n", pkg)
	if len(types) > 0 {
		b.WriteString("\nimport (\n")
		imports := map[string]string{}
		for _, t := range types {
			imports[t.alias] = t.importPath
		}
		aliases := make([]string, 0, len(imports))
		for alias := range imports {
			aliases = append(aliases, alias)
		}
		sort.Strings(aliases)
		for _, alias := range aliases {
			fmt.Fprintf(&b, "%s %q\n", alias, imports[alias])
		}
		b.WriteString(")\n")
		for _, t := range types {
			fmt.Fprintf(&b, "\ntype %s struct { %s.%s }\n", t.name, t.alias, t.name)
		}
	}
	return genutil.WriteGo(out, b.Bytes())
}

func embedsEntSchema(st *ast.StructType) bool {
	for _, field := range st.Fields.List {
		if len(field.Names) != 0 {
			continue
		}
		if sel, ok := field.Type.(*ast.SelectorExpr); ok && sel.Sel.Name == "Schema" {
			if pkg, ok := sel.X.(*ast.Ident); ok && pkg.Name == "ent" {
				return true
			}
		}
	}
	return false
}

func checkLocalCollisions(dir, out string, generated map[string]bool) error {
	files, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		return err
	}
	for _, file := range files {
		if filepath.Clean(file) == filepath.Clean(out) || strings.HasSuffix(file, "_test.go") {
			continue
		}
		parsed, err := parser.ParseFile(token.NewFileSet(), file, nil, 0)
		if err != nil {
			return err
		}
		for _, decl := range parsed.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				name := spec.(*ast.TypeSpec).Name.Name
				if generated[name] {
					return fmt.Errorf("schema type %s collides with %s", name, file)
				}
			}
		}
	}
	return nil
}
