package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"

	"github.com/wuwuseo/cmf/app/internal/genutil"
)

var appCodePattern = regexp.MustCompile(`^[a-z][a-z0-9]*$`)

func main() {
	dir := flag.String("dir", ".", "feature set directory")
	out := flag.String("out", "zz_generated.go", "generated file")
	pkg := flag.String("pkg", "apps", "output package")
	flag.Parse()
	if err := generate(*dir, *out, *pkg); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(dir, out, pkg string) error {
	base, err := genutil.ModuleImport(dir)
	if err != nil {
		return err
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	var imports []string
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		if _, err := os.Stat(filepath.Join(dir, entry.Name(), "app.go")); err == nil {
			if !appCodePattern.MatchString(entry.Name()) {
				return fmt.Errorf("invalid app directory %q", entry.Name())
			}
			imports = append(imports, base+"/"+entry.Name())
		} else if !os.IsNotExist(err) {
			return err
		}
	}
	sort.Strings(imports)
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by appgen; DO NOT EDIT.\npackage %s\n", pkg)
	if len(imports) > 0 {
		b.WriteString("\nimport (\n")
		for _, path := range imports {
			fmt.Fprintf(&b, "_ %q\n", path)
		}
		b.WriteString(")\n")
	}
	return genutil.WriteGo(out, b.Bytes())
}
